# modules/strategy_profiles.py

strategies = {
    "opening": {
        "limit": 100,
        "min_score": 4,
        "include_weak": True,
        "use_rsi": True,
        "use_macd": True,
        "use_kd": True,
        "use_ma60": False,
        "use_bollinger": False,
        "use_institutional": False,
        "use_eps": False,
        "use_dividend": False,
    },
    "intraday": {
        "limit": 150,
        "min_score": 3.5,
        "include_weak": True,
        "use_rsi": True,
        "use_macd": True,
        "use_kd": True,
        "use_ma60": True,
        "use_bollinger": True,
        "use_institutional": False,
        "use_eps": False,
        "use_dividend": False,
    },
    "dividend": {
        "limit": 200,
        "min_score": 3,
        "include_weak": True,
        "use_rsi": False,
        "use_macd": True,
        "use_kd": False,
        "use_ma60": True,
        "use_bollinger": False,
        "use_institutional": True,
        "use_eps": True,
        "use_dividend": True,
    },
    "closing": {
        "limit": 400,
        "min_score": 4,
        "include_weak": True,
        "use_rsi": True,
        "use_macd": True,
        "use_kd": True,
        "use_ma60": True,
        "use_bollinger": True,
        "use_institutional": True,
        "use_eps": True,
        "use_dividend": True,
    }
}
