name: 早盤推薦（09:00）

on:
  schedule:
    - cron: '0 1 * * 1-5'  # 台灣09:00 = UTC+8 → UTC 01:00
  workflow_dispatch:

jobs:
  run-morning:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 增加執行超時設定
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set timezone
        run: |
          echo "Setting timezone to Asia/Taipei"
          echo "TZ=Asia/Taipei" >> $GITHUB_ENV
      - name: Debug date
        run: |
          echo "Current time: $(date)"
          echo "Current day: $(date +%u)"  # 1=Mon, 7=Sun
      - name: Test network connection
        run: |
          echo "測試網絡連接..."
          ping -c 4 finance.yahoo.com || echo "ping 失敗但繼續執行"
          curl -I https://finance.yahoo.com || echo "curl 失敗但繼續執行"
      - name: Run Morning Recommendations
        env:
          GOOGLE_JSON_KEY: ${{ secrets.GOOGLE_JSON_KEY }}
          FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          YAHOO_FINANCE_RETRY_ATTEMPTS: "5"  # 增加重試次數的環境變數
          YAHOO_FINANCE_BATCH_DELAY: "5"     # 批次間延遲的環境變數
          TZ: "Asia/Taipei"  # 設置環境變量
        run: python main.py --mode=morning
