name: 盤中監控（10:30）

on:
  schedule:
    - cron: '30 2 * * 1-5'  # 台灣10:30 = UTC+8 → UTC 02:30
  workflow_dispatch:

jobs:
  run-intraday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Intraday Monitor
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python main.py --mode=intraday
