name: 收盤分析（15:00）

on:
  schedule:
    - cron: '0 7 * * 1-5'  # 台灣15:00 = UTC+8 → UTC 07:00
  workflow_dispatch:

jobs:
  run-closing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Closing Summary
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python main.py --mode=closing
