name: push_0900

on:
  schedule:
    - cron: '0 1 * * *'  # 每天台灣時間 09:00（UTC+8）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

     - name: Run push script
  run: python3 ./twstock-line-bot/main.py --time 0900

